# Generated by Django 4.1.7 on 2023-02-18 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dpto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDpto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='gestionCursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCurso', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
                ('duracion', models.CharField(max_length=3)),
                ('estado', models.BooleanField(default=False)),
                ('nombreDpto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.dpto')),
            ],
        ),
    ]
